language: node_js
node_js:
  - "4.4.1"

before_install:
  - git config --global push.default matching
  - git config --global user.name "zjdian" 
  - git config --global user.email "947879645@qq.com"

install:
  - npm install hexo-cli -g
  - npm install hexo --save
  - npm install
  - npm install hexo-generator-feed --save
  - npm install hexo-deployer-git --save
  - npm install hexo-renderer-ejs --save
  - npm install hexo-renderer-stylus --save
  - npm install hexo-renderer-marked --save
  - npm install hexo-renderer-sass --save
  - npm install hexo-generator-searchdb --save
  - npm install -S hexo-generator-json-content@1 --save

script:
  - hexo clean
  - hexo generate

after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force https://$DEPLOY_REPO@github.com/zjdian/zjdian.github.io.git master

branches:
  only:
    - dataonion
cache:
  directories:
   - node_modules